name: Staging Phase

on:
  push:
    branches:
      - "main"

env:
  DOCKER_IMAGE_REPOSITORY_NAME: alta-mini-project
  DOCKER_IMAGE_TAG_NAME: dev
  DOCKER_SERVICE_NAME: backend-service

jobs:
  integration_testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Get Tag Name
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      - name: Prepare environment for Go
        uses: actions/setup-go@v3
        with:
          go-version: ">=1.18.0"
      - name: Run unit test
        run: go test -cover -v ./...
  build_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.DOCKER_IMAGE_REPOSITORY_NAME }}:${{ env.DOCKER_IMAGE_TAG_NAME }}-${{ github.sha }},${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.DOCKER_IMAGE_REPOSITORY_NAME }}:${{ env.DOCKER_IMAGE_TAG_NAME }}-latest
      - name: Executing remote command using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_STAGING_SERVER }}
          username: ${{ secrets.SSH_STAGING_USERNAME }}
          key: ${{ secrets.SSH_STAGING_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PRODUCTION_PORT }}
          script: |
            cd cd mini-project-alterra/dev
            docker compose rm -sf ${{ env.DOCKER_SERVICE_NAME }}
            docker rmi ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.DOCKER_IMAGE_REPOSITORY_NAME }}:${{ env.DOCKER_IMAGE_TAG_NAME }}-latest
            docker compose up -d ${{ env.DOCKER_SERVICE_NAME }}
